/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.8
 * Generated at: 2018-09-13 10:55:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/app/lipapay-home/war/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098711090000L));
    _jspx_dependants.put("/WEB-INF/home/common/header.jsp", Long.valueOf(1529460860000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.7.RELEASE.jar", Long.valueOf(1497508922000L));
    _jspx_dependants.put("jar:file:/app/lipapay-home/war/WEB-INF/lib/spring-webmvc-4.0.7.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1409790786000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1505716972000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    ");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/bootstrap.min.css?v=20180607\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/header.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/footer.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/site.min.css\">\n");
      out.write("\n");
      out.write("<meta name=\"robots\" content=\"all\"/>\n");
      out.write("<meta name=\"geo.placename\" content=\"LipaPay\">\n");
      out.write("<meta name=\"url\" content=\"https://www.lipapay.com/\">\n");
      out.write("<meta name=\"generator\" content=\"SEOmatic\">\n");
      out.write("<link rel=\"canonical\" href=\"https://www.lipapay.com/\">\n");
      out.write("<meta name=\"dcterms.Identifier\" content=\"/\">\n");
      out.write("<meta name=\"dcterms.Format\" content=\"text/html\">\n");
      out.write("<meta name=\"dcterms.Relation\" content=\"LipaPay\">\n");
      out.write("<meta name=\"dcterms.Language\" content=\"en_us\">\n");
      out.write("<meta name=\"dcterms.Publisher\" content=\"LipaPay\">\n");
      out.write("<meta name=\"dcterms.Type\" content=\"text/html\">\n");
      out.write("<meta name=\"dcterms.Coverage\" content=\"https://www.lipapay.com/\">\n");
      out.write("<meta name=\"dcterms.Rights\" content=\"Copyright Â©2017 Lipapay.\">\n");
      out.write("<meta name=\"dcterms.Title\" content=\"Accept Payments Online\">\n");
      out.write("<meta name=\"dcterms.Subject\" content=\" Nigeria payment, Kenya payment, Africa payment, payment gateway,Online payment\">\n");
      out.write("<meta name=\"dcterms.Contributor\" content=\"LipaPay\">\n");
      out.write("<meta name=\"dcterms.Description\" content=\"Lipapay aims to help millions of Africa business to collect payment in an easy, fast, reliable and smart way. Customer is able to make payment using Credit card, bank card, or mobile money, and even a link sent from an email.\">\n");
      out.write("\n");
      out.write("<!-- facebook -->\n");
      out.write("<meta property=\"og:url\" content=\"https://www.lipapay.com\" />\n");
      out.write("<meta property=\"og:type\" content=\"website\" />\n");
      out.write("<meta property=\"og:title\" content=\"Kenya Payment Gateway  - LipaPay\" />\n");
      out.write("<meta property=\"og:locale\" content=\"en_us\">\n");
      out.write("<meta property=\"og:description\" content=\"Lipapay aims to help millions of Africa business to collect payment in an easy, fast, reliable and smart way. Customer is able to make payment using Credit card, bank card, or mobile money, and even a link sent from an email.\" />\n");
      out.write("<meta property=\"og:see_also\" content=\"https://twitter.com/lipapay\">\n");
      out.write("<meta property=\"og:see_also\" content=\"https://www.facebook.com/lipapay\">\n");
      out.write("<meta property=\"og:see_also\" content=\"https://www.linkedin.com/company/lipapay/\">\n");
      out.write("<meta property=\"og:see_also\" content=\"https://plus.google.com/107955390710514784279\">\n");
      out.write("\n");
      out.write("<!-- Twitter Card -->\n");
      out.write("<meta property=\"twitter:card\" content=\"summary\">\n");
      out.write("<meta property=\"twitter:site\" content=\"@lipapay\">\n");
      out.write("<meta property=\"twitter:title\" content=\"LipaPay - Accept Payments Online\">\n");
      out.write("<meta property=\"twitter:description\" content=\"Lipapay aims to help millions of Africa business to collect payment in an easy, fast, reliable and smart way. Customer is able to make payment using Credit card, bank card, or mobile money, and even a link sent from an email.\">\n");
      out.write("\n");
      out.write("<!-- Global site tag (gtag.js) - Google Analytics -->\n");
      out.write("<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-102189163-1\"></script>\n");
      out.write("<script>\n");
      out.write("    window.dataLayer = window.dataLayer || [];\n");
      out.write("    function gtag(){dataLayer.push(arguments);}\n");
      out.write("    gtag('js', new Date());\n");
      out.write("\n");
      out.write("    gtag('config', 'UA-102189163-1');\n");
      out.write("</script>");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"bodyContainer\" id=\"bodyContainer\">\n");
      out.write("    <div class=\"wrap\">\n");
      out.write("        <div class=\"content\">\n");
      out.write("            <div class=\"mc_top\">\n");
      out.write("                <div class=\"container text-center\">\n");
      out.write("                    <div class=\"mc_top_logo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/mcLogo.png\" alt=\"\"></div>\n");
      out.write("                    <div class=\"mc_top_title\">\n");
      out.write("                        <em class=\"em-ico\"></em>\n");
      out.write("                        <a href=\"https://www.mcafeesecure.com/verify?host=lipapay.com\" target=\"_blank\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/mcIco.png\">\n");
      out.write("                        </a>\n");
      out.write("                        McAfee certification\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mc_top_img\">\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/2.png\">\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/1.png\">\n");
      out.write("                    </div>\n");
      out.write("                    <p class=\"mc_top_text\">Lipapay is a remarkable payment company</p>\n");
      out.write("                    <p class=\"mc_top_text\">owned by Kilimall and secured by McAfee certification.</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mc_main\">\n");
      out.write("                <div class=\"container mc_payment text-center\">\n");
      out.write("                    <div class=\"mc_payment_title\">PAYMENT PARTNERS</div>\n");
      out.write("                    <p class=\"mc_payment_text\">Security is at the heart of our service.</p>\n");
      out.write("                    <p class=\"mc_payment_text\">We have a world-class anti-fraud system to protect you and your customers.</p>\n");
      out.write("                    <p class=\"mc_payment_text\">At the same time, we comply with third-party payment industry</p>\n");
      out.write("                    <p class=\"mc_payment_text\">data security standards to guard your business and enhance customer confidence.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"container mc_payment_partner\">\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/mpesa.png\"></div>\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/MTN.png\"></div>\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/airtel.png\"></div>\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/MasterCard.png\"></div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/VISA.png\"></div>\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/Interswitch.png\"></div>\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/CyberSource.png\"></div>\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/UBA.png\"></div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/ZENITH.png\"></div>\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/CreditBank.png\"></div>\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/Ecobank.png\"></div>\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mc/KCB.png\"></div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"site_bot\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"site_bot_box\">\n");
      out.write("                <div class=\"site_bot_part\">\n");
      out.write("                    <p><a href=\"/privacy.html?langType=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.langType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</a>\n");
      out.write("                    <em>|</em>\n");
      out.write("                    <a href=\"/contactus.html?langType=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.langType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      if (_jspx_meth_spring_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("</a></p>\n");
      out.write("                    <span>© Copyright LipaPay 2018</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"site_bot_part\">\n");
      out.write("                    <a href=\"https://www.mcafeesecure.com/verify?host=lipapay.com\" target=\"_blank\">\n");
      out.write("                        <img class=\"site_secure_ico\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/mcIco.png\" alt=\"\">\n");
      out.write("                    </a>\n");
      out.write("                    <img class=\"site_secure_ico\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/trustedIco.png\" alt=\"\">\n");
      out.write("                    <img class=\"site_secure_ico\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("./images/sslIco.png\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.2.1.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdnURI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    try {
      _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f0.setParent(null);
      // /WEB-INF/home/mc.jsp(64,81) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f0.setCode("foot.privacy");
      int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
        if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    try {
      _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f1.setParent(null);
      // /WEB-INF/home/mc.jsp(67,80) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f1.setCode("foot.contact");
      int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
        if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
    }
    return false;
  }
}
